export const ADMIN_QUESTON_GET_OPTION_TOPIC = "ADMIN_QUESTON_GET_OPTION_TOPIC";
export const ADMIN_QUESTON_GET_OPTION_QUESTION_SET =
	"ADMIN_QUESTON_GET_OPTION_QUESTION_SET";
export const ADMIN_QUESTON_GET_LIST_QUESTION =
	"ADMIN_QUESTON_GET_LIST_QUESTION";
export const ADMIN_QUESTON_CREATE_UPDATE_QUESTION_SET =
	"ADMIN_QUESTON_CREATE_UPDATE_QUESTION_SET";
export const ADMIN_QUESTON_ADD_QUESTION = "ADMIN_QUESTON_ADD_QUESTION";
