export const ADMIN_TOPIC_GET_ALL_TOPIC = "ADMIN_TOPIC_GET_ALL_TOPIC";
export const ADMIN_TOPIC_GET_ALL_TOPIC_DONE = "ADMIN_TOPIC_GET_ALL_TOPIC_DONE";

export const ADMIN_TOPIC_ADD_NEW_TOPIC = "ADMIN_TOPIC_ADD_NEW_TOPIC";
export const ADMIN_TOPIC_UPDATE_TOPIC = "ADMIN_TOPIC_UPDATE_TOPIC";
