export const AUTH_ACCOUNT_LOGIN = "AUTH_ACCOUNT_LOGIN";
export const AUTH_ACCOUNT_LOGIN_DONE = "AUTH_ACCOUNT_LOGIN_DONE";

export const ADMIN_ACCOUNT_GET_ALL_ACCOUNT = "ADMIN_ACCOUNT_GET_ALL_ACCOUNT";
export const ADMIN_ACCOUNT_GET_ALL_ACCOUNT_DONE =
	"ADMIN_ACCOUNT_GET_ALL_ACCOUNT_DONE";

export const ADMIN_ACCOUNT_UPDATE_INFO_USER = "ADMIN_ACCOUNT_UPDATE_INFO_USER";
